issuer: http://localhost:18080/dex
storage:
  type: sqlite3
  config:
    file: /etc/ood/dex/dex.db
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
staticClients:
  - id: localhost
    redirectURIs:
      - http://localhost:18080/oidc
    name: OnDemand
    secret: __OOD_LOCAL_DEX_CLIENT_SECRET__
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true
staticPasswords:
  - email: misaki@localhost
    hash: "__OOD_LOCAL_PASSWORD_HASH__"
    username: misaki
    userID: "__OOD_LOCAL_USER_ID__"
frontend:
  dir: /usr/share/ondemand-dex/web
  theme: ondemand
