issuer: https://eecorehpc.ee.ntu.edu.tw/dex
storage:
  type: sqlite3
  config:
    file: /etc/ood/dex/dex.db
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
staticClients:
  - id: eecorehpc.ee.ntu.edu.tw
    redirectURIs:
      - https://eecorehpc.ee.ntu.edu.tw/oidc
      - https://eecorehpc.ee.ntu.edu.tw:443/oidc
    name: OnDemand
    secret: __OOD_DEX_CLIENT_SECRET__
oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
connectors:
  - type: saml
    id: ntu-adfs
    name: 台大帳號 (NTU SSO)
    config:
      ssoURL: https://adfs.ntu.edu.tw/adfs/ls/
      ca: /etc/ood/dex/adfs-ntu.crt
      redirectURI: https://eecorehpc.ee.ntu.edu.tw/dex/callback
      entityIssuer: https://eecorehpc.ee.ntu.edu.tw/dex/callback
      userIDAttr: "http://www.ntu.edu.tw/AccountName"
      usernameAttr: "http://www.ntu.edu.tw/AccountName"
      nameAttr: "http://www.ntu.edu.tw/ChineseName"
      emailAttr: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
      nameIDPolicyFormat: unspecified
frontend:
  dir: /usr/share/ondemand-dex/web
  theme: ondemand
